scheme: Gemini
darkmode: true
giscus:
  enable: true
  repo: Linniem/linniem.github.io
  repo_id: R_kgDOHXyKlQ
  category: General
  category_id: DIC_kwDOHXyKlc4CSyMO
  # Available values: pathname | url | title | og:title
  mapping: pathname
  # Available values: 0 | 1 
  reactions_enabled: 1
   # Available values: 0 | 1 
  emit_metadata: 1
  # Available values: light | dark | dark_high_contrast | transparent_dark | preferred-color-scheme
  theme: dark
  # Available values: en | zh-C
  lang: zh-TW
  # Available value: anonymous
  crossorigin: anonymous
  # Place the comment box above the comments
  input_position: top
  # Load the comments lazily
  loading: lazy